apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuck-demo
  labels:
    app: stuck-demo
spec:
  selector:
    matchLabels:
      app: stuck-demo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stuck-demo
    spec:
      hostNetwork: true
      containers:
        - name: stuck-demo
          image: stuck-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 19999
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SERVER_PORT
              value: '19999'
          resources:
            limits:
              memory: 1Gi